**installing** **library** 

In [ ]:
pip install pythainlp


In [ ]:
from pythainlp.tokenize import word_tokenize
import pandas as pd
import pythainlp.corpus as pt
import matplotlib.pyplot as plt 
from wordcloud import WordCloud
import numpy as np 
#import pythainlp.tokenize import 
import re



read data / just take a look at data

In [ ]:
train = pd.read_csv('trainthai.csv')
#test  = pd.read_csv('testthai.csv')

In [ ]:
print(train.shape)

(201, 5)


In [ ]:
print(train.isnull().sum())

id        0
title     0
author    0
text      0
label     0
dtype: int64


fill nullspace with NA / make new column

In [ ]:
#test=test.fillna(' ')
train=train.fillna(' ')
#test['total']=test['title']+' '+test['author']+test['text']
train['total']=train['title']+' '+train['author']+train['text']
train.head()

**Wordcloud**

In [ ]:
real_words = ''
stopwords = pt.thai_stopwords() 
  
# iterate through the csv file 
for val in train[train['label']==1].total: 
  
    # split the value 
    tokens = val.split() 
      
      
    real_words += " ".join(tokens)+" "

word_tokenize(real_words)

In [ ]:
real_words = clean_msg(real_words)
real_words

'กลุ่มไทยภักดี นัดรวมพลที่สวนลุมพินี หมอวรงค์ อ่านแถลงการณ์ ค้านแก้รัฐธรรมนูญ ปี2560 แจง 14 เหตุผล แม้ไม่แตะหมวด12 ก็ไม่ยอมรับ ห่วงพวกจ้องล้มล้างสถาบัน ยืนยันชุมนุม ไม่ใช่สร้างม็อบชนม็อบ เชื่อประเทศมีทางออก โดยไม่ต้องปฏิวัติ ด้าน อุ๊ หฤทัย ห่วงไทยเกิดมิคสัญญี เกิดความรุนแรง voicetvกลุ่มไทยภักดี นัดรวมพลสวมเสื้อสีเหลือง แสดงจุดยืนปกป้องสถาบัน พร้อมคัดค้านการแก้ไขรัฐธรรมนูญ ฉบับปี 2560 ที่สวนลุมพินี โดยมี นพวรงค์ เดชกิจวิกรม หฤทัย ม่วงบุญศรี หรือ อุ๊ เป็นแกนนำ ซึ่งทางแกนนำได้นำรถมาปราศรัย ก่อนที่ในเวลา 1800 น จะร่วมเคารพธงชาติพร้อมกัน และยุติการชุมนุม ไม่ปักหลักค้างคืน ทั้งนี้ นพวรงค์ ได้อ่านแถลงการณ์คัดค้านการแก้ไขรัฐธรรมนูญเพื่อร่างใหม่โดยตั้ง สสร โดยยก 14 เหตุผล ไม่ควรแก้ไขรัฐธรรมนูญหลักๆ คือ เป็นรัฐธรรมนูญที่ผ่านการลงประชามติ เสียงข้างมาก 168 ล้านเสียง มี พรรคการเมืองบางพรรค จ้องอาศัยล้มล้างรัฐธรรมนูญ เพื่อนำไปสู่การล้มล้างสถาบัน และแบ่งแยกประเทศ โดยอาศัยม็อบมากดดัน นอกจากนี้ รัฐธรรมนูญยังมีจุดเด่นเรื่องของการปรับโกง ตัดสิทธิ์สส ตลอดชีวิตในคดีทุจริต ซึ่งนักการเมืองไม่ชอบ ขณะเดียวกัน 

In [ ]:
wordcloud = WordCloud(font_path='THSarabunNew.ttf',
                      stopwords = pt.thai_stopwords(),
                      background_color="white",
                      width=1024, # กว้าง
                      height=768, # ยาว
                      collocations=False,
                      regexp=r"[\u0E00-\u0E7Fa-zA-Z']+"
                      )
wordcloud.generate(' '.join(word_tokenize(real_words)))
plt.figure(figsize = (8, 8)) 
plt.imshow(wordcloud, cmap=plt.cm.gray, interpolation='bilinear')
plt.axis("off")
plt.show()



**text** **tokenize**

In [ ]:
#tokenize 
text = """
พฤกษารุกขาชาติ                         จักองอาจยืนอยู่มั่น

อาจสู้ช้างตกมัน                                      เพราะรากนั้นยึดผืนดิน                

วัฒนธรรมอันล้ำเลิศ                    สุดประเสริฐคืองานศิลป์

ประเพณีในถิ่น                                        ดวงวิญญาณสืบสานมา

คือรากของชาติพันธุ์                     อันตั้งมั่นในโลกา

ถือวัตรปฏิบัติมา                                     ทุกภาษามีของตน

หากรากของไม้กล้า                      แม้ช้างป่าในไพรสณฑ์

ทายท้ามาประจญ                                    กี่ช้างชนก็ทนไหว

แต่หากมีปลวกร้าย                      บ่อนทำลายจากภายใน

สิ้นรากย่อมล้มไป                                    ไม่ต้องรอช้างงารี

วัฒนธรรมบำรุงชาติ                    เหมือนปุ๋ยราดพฤกษาสี

รากแกร่งแข็งแรงดี                                  มิพักที่จะผลิใบ

หากไทยไม่ใฝ่รักษ์                        คุณค่าจักหายไปไหน

เหมือนไม้ไม่ทนภัย                                  จักล้มไปไม่เพิ่มพูน

สมบัติชาติไทยนั้น                       ยิ่งนับวันยิ่งเสื่อมสูญ

แม้ไทยไม่เกื้อกูล                                      ใครอาดูรเมื่อสิ้นไทย


"""
word_tokenize(text)

In [ ]:
stopwords = pt.thai_stopwords() 
stopwords

In [ ]:
texttest = word_tokenize(text)
texttest = [w for w in texttest if w not in pt.thai_stopwords()]
texttest

1) cleaning data

In [ ]:
import re
import string

def clean_msg(msg):
    
    
    # ลบ text ที่อยู่ในวงเล็บ <> ทั้งหมด
    msg = re.sub(r'<.*?>','', msg)
    
    # ลบ hashtag
    msg = re.sub(r'#','',msg)
    
    # ลบ เครื่องหมายคำพูด (punctuation)
    for c in string.punctuation:
        msg = re.sub(r'\{}'.format(c),'',msg)
    
    # ลบ separator เช่น \n \t
    msg = ' '.join(msg.split())
    
    return msg



**2 ) Stopwords**

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.corpus import words
from pythainlp.corpus import wordnet
nltk.download('stopwords')
stop_words = stopwords.words('english')
p_stemmer = PorterStemmer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
def split_word(text):
            
    
    tokens = word_tokenize(text,engine='newmm')
    
    # Remove stop words ภาษาไทย และภาษาอังกฤษ
    tokens = [i for i in tokens if not i in pt.thai_stopwords() and not i in stop_words]
    
    # หารากศัพท์ภาษาไทย และภาษาอังกฤษ
    # English
    tokens = [p_stemmer.stem(i) for i in tokens]
    
    # Thai
    tokens_temp=[]
    for i in tokens:
        w_syn = wordnet.synsets(i)
        if (len(w_syn)>0) and (len(w_syn[0].lemma_names('tha'))>0):
            tokens_temp.append(w_syn[0].lemma_names('tha')[0])
        else:
            tokens_temp.append(i)
    
    tokens = tokens_temp
    
    # ลบตัวเลข
    tokens = [i for i in tokens if not i.isnumeric()]
    
    # ลบช่องว่าง
    tokens = [i for i in tokens if not ' ' in i]

    return tokens

print(split_word(clean_msg(train['total'].iloc[0])))

['ไท', 'ภักดี', 'นัด', 'รวมพล', 'สวน', 'ลุมพินี', 'ดร.', 'วรงค์', 'อ่าน', 'แถลงการณ์', 'ค้าน', 'แก้', 'รัฐธรรมนูญ', 'ปี', 'แจง', 'แตะ', 'หมวด', 'ห่วง', 'จ้อง', 'ล้มล้าง', 'สถาบัน', 'ชุมนุม', 'สร้าง', 'ม็อบ', 'ชน', 'ม็อบ', 'รัฐ', 'ทาง', 'ไม่ต้อง', 'ปฏิวัติ', 'อุ๊', 'หฤทัย', 'ห่วง', 'ไท', 'มิคสัญญี', 'ความรุนแรง', 'voicetv', 'ไท', 'ภักดี', 'นัด', 'รวมพล', 'สวม', 'เสื้อ', 'เหลือง', 'จุดยืน', 'ปกป้อง', 'สถาบัน', 'คัดค้าน', 'รัฐธรรมนูญ', 'ฉบับ', 'ปี', 'สวน', 'ลุมพินี', 'นพ', 'วรงค์', 'เดช', 'กิจ', 'วิกรม', 'หฤทัย', 'ม่วง', 'บุญ', 'ศรี', 'อุ๊', 'แกนนำ', 'แกนนำ', 'รถ', 'ปราศรัย', 'ก่อนที่', 'กาล', 'น', 'เคารพ', 'ธงชาติ', 'ยุติ', 'ชุมนุม', 'ปักหลัก', 'ค้างคืน', 'นพ', 'วรงค์', 'อ่าน', 'แถลงการณ์', 'คัดค้าน', 'รัฐธรรมนูญ', 'ร่าง', 'สส', 'ร', 'รัฐธรรมนูญ', 'หลัก', 'รัฐธรรมนูญ', 'ประชามติ', 'เสียงข้างมาก', 'ล้าน', 'เสียง', 'พรรค', 'พรรค', 'จ้อง', 'อยู่', 'ล้มล้าง', 'รัฐธรรมนูญ', 'นำไปสู่', 'ล้มล้าง', 'สถาบัน', 'แบ่งแยก', 'รัฐ', 'อยู่', 'ม็อบ', 'บีบ', 'รัฐธรรมนูญ', 'ยังมี', 'จุดเด่น', 'เรื่อง', 'โก

In [ ]:
train = train[['total','label']]
train["total"]

In [ ]:
tokens_list = [split_word(txt) for txt in train['total']]
tokens_list

**3 ) NLP technique**

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

In [ ]:
X_train = train['total']
Y_train = train['label']

**CountVectorizer**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
tokens_list_j = [','.join(tkn) for tkn in tokens_list]
cvec = CountVectorizer(analyzer=lambda x:x.split(','))
c_feat = cvec.fit_transform(tokens_list_j)
vocab  = cvec.vocabulary_

In [ ]:
vocab

In [ ]:
c_feat[:,:].todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

**TfidfVectorizer**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tvec = TfidfVectorizer(analyzer=lambda x:x.split(','),)
t_feat = tvec.fit_transform(tokens_list_j)
tfidf = TfidfTransformer(norm="l2")
tfidf.fit(t_feat)
tf_idf_matrix = tfidf.fit_transform(t_feat)
tvec.vocabulary_



In [ ]:
t_feat[:,:].todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
print(len(tvec.idf_),len(tvec.vocabulary_))

4647 4647


In [ ]:
c_feat[:,:].todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])


**4) Modeling / prediction model**

In [ ]:
#test_counts = cvec.transform(train['total'].values)
#test_tfidf = tfidf.transform(test_counts)

#split in samples
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(tf_idf_matrix, Y_train, random_state=0)

**Logistic Regression**/ **option 1**

In [ ]:
logreg = LogisticRegression(C=1e5)
logreg.fit(X_train, y_train)
pred = logreg.predict(X_test)
print('Accuracy of Lasso classifier on training set: {:.2f}'
     .format(logreg.score(X_train, y_train)))
print('Accuracy of Lasso classifier on test set: {:.2f}'
     .format(logreg.score(X_test, y_test)))
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, pred)
cm

Accuracy of Lasso classifier on training set: 1.00
Accuracy of Lasso classifier on test set: 1.00


array([[27,  0],
       [ 0, 24]])

**Multinomial(Naives bayes)** / **option 2** 

In [ ]:
from sklearn.naive_bayes import MultinomialNB

NB = MultinomialNB()
NB.fit(X_train, y_train)
pred = NB.predict(X_test)
print('Accuracy of NB  classifier on training set: {:.2f}'
     .format(NB.score(X_train, y_train)))
print('Accuracy of NB classifier on test set: {:.2f}'
     .format(NB.score(X_test, y_test)))
cm = confusion_matrix(y_test, pred)
cm

Accuracy of NB  classifier on training set: 1.00
Accuracy of NB classifier on test set: 0.98


array([[27,  0],
       [ 1, 23]])

In [ ]:
X_train

**pipeline**

In [ ]:
X_train = train['total']
Y_train = train['label']

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.externals import joblib
from sklearn import linear_model
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
pipeline = Pipeline([
    ('vect', CountVectorizer()),
    ('tfidf', TfidfTransformer(norm='l2')),
    ('clf', MultinomialNB()),
])

In [ ]:
pipeline.fit(X_train, Y_train)

In [ ]:
#saving the pipeline
filename = 'pipeline.sav'
joblib.dump(pipeline, filename)

['pipeline.sav']

In [ ]:
filename = './pipeline.sav'

In [ ]:
loaded_model = joblib.load(filename)
result = loaded_model.predict(["เล่นมือถือนานๆ ทำให้หน้าเบี้ยวผิดรูป"])
if result == 0 :
  print("fake")
if result == 1 :
  print("real")
print(result)

fake
[0]


# Tutorial 
https://www.youtube.com/watch?v=z_mNVoBcMjM&t=257s

#NLP
https://www.youtube.com/watch?v=xvqsFTUsOmc

#tutorial 2
https://www.youtube.com/watch?v=xyq-zYr1cnI


STATQuest